//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutlookSafetyChex.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool opt_Use_CACHE {
            get {
                return ((bool)(this["opt_Use_CACHE"]));
            }
            set {
                this["opt_Use_CACHE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool opt_Lookup_WHOIS {
            get {
                return ((bool)(this["opt_Lookup_WHOIS"]));
            }
            set {
                this["opt_Lookup_WHOIS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool opt_Lookup_DNSBL {
            get {
                return ((bool)(this["opt_Lookup_DNSBL"]));
            }
            set {
                this["opt_Lookup_DNSBL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool opt_Lookup_HIBP {
            get {
                return ((bool)(this["opt_Lookup_HIBP"]));
            }
            set {
                this["opt_Lookup_HIBP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool opt_Force_REFRESH {
            get {
                return ((bool)(this["opt_Force_REFRESH"]));
            }
            set {
                this["opt_Force_REFRESH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool opt_Lookup_CONTACTS {
            get {
                return ((bool)(this["opt_Lookup_CONTACTS"]));
            }
            set {
                this["opt_Lookup_CONTACTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool opt_Flag_UNKNOWN_CONTACTS {
            get {
                return ((bool)(this["opt_Flag_UNKNOWN_CONTACTS"]));
            }
            set {
                this["opt_Flag_UNKNOWN_CONTACTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool opt_Local_BLACKLIST {
            get {
                return ((bool)(this["opt_Local_BLACKLIST"]));
            }
            set {
                this["opt_Local_BLACKLIST"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool opt_Local_WHITELIST {
            get {
                return ((bool)(this["opt_Local_WHITELIST"]));
            }
            set {
                this["opt_Local_WHITELIST"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool opt_DeepInspect_LINKS {
            get {
                return ((bool)(this["opt_DeepInspect_LINKS"]));
            }
            set {
                this["opt_DeepInspect_LINKS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool opt_DeepInspect_ATTACHMENTS {
            get {
                return ((bool)(this["opt_DeepInspect_ATTACHMENTS"]));
            }
            set {
                this["opt_DeepInspect_ATTACHMENTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool test_Contacts {
            get {
                return ((bool)(this["test_Contacts"]));
            }
            set {
                this["test_Contacts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool test_Routes {
            get {
                return ((bool)(this["test_Routes"]));
            }
            set {
                this["test_Routes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool test_Links {
            get {
                return ((bool)(this["test_Links"]));
            }
            set {
                this["test_Links"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool test_Attachments {
            get {
                return ((bool)(this["test_Attachments"]));
            }
            set {
                this["test_Attachments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>.cn</string>
  <string>.tk</string>
  <string>.ru</string>
  <string>.cm</string>
  <string>.in</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection local_Blacklist {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["local_Blacklist"]));
            }
            set {
                this["local_Blacklist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>goog.le</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection local_Whitelist {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["local_Whitelist"]));
            }
            set {
                this["local_Whitelist"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>.org</string>
  <string>.net</string>
  <string>.com</string>
  <string>.edu</string>
  <string>.gov</string>
  <string>.mil</string>
  <string>.us</string>
  <string>.co.uk</string>
  <string>.ca</string>
  <string>.nyc</string>
  <string>.co</string>
  <string>bit.ly</string>
  <string>goog.le</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection base_Whitelist {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["base_Whitelist"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>.cn</string>
  <string>.tk</string>
  <string>.ru</string>
  <string>.cm</string>
  <string>.in</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection base_Blacklist {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["base_Blacklist"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(";")]
        public string list_Delimiter {
            get {
                return ((string)(this["list_Delimiter"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" />")]
        public global::System.Collections.Specialized.StringCollection cache_TLDs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["cache_TLDs"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool test_Body {
            get {
                return ((bool)(this["test_Body"]));
            }
            set {
                this["test_Body"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public uint log_Level {
            get {
                return ((uint)(this["log_Level"]));
            }
            set {
                this["log_Level"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool opt_ShowLog {
            get {
                return ((bool)(this["opt_ShowLog"]));
            }
            set {
                this["opt_ShowLog"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>multi.surbl.org</string>
  <string>multi.uribl.com</string>
  <string>sbl-xbl.spamhaus.org</string>
  <string>bl.spamcop.net</string>
  <string>cbl.abuseat.org</string>
  <string>multirbl.valli.org</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DNSBL_sites {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DNSBL_sites"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>text/html</string>
  <string>text/plain</string>
  <string>application/rtf</string>
  <string>multipart/alternative</string>
  <string>multipart/related</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection common_MIMETYPEs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["common_MIMETYPEs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>utf-8</string>
  <string>utf-16</string>
  <string>windows-1250</string>
  <string>windows-1252</string>
  <string>us-ascii</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection common_CODEPAGEs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["common_CODEPAGEs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>en-US</string>\r\n  <string>en</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection common_CULTURESs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["common_CULTURESs"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool test_Headers {
            get {
                return ((bool)(this["test_Headers"]));
            }
            set {
                this["test_Headers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool opt_Lookup_Cultures {
            get {
                return ((bool)(this["opt_Lookup_Cultures"]));
            }
            set {
                this["opt_Lookup_Cultures"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool opt_Lookup_Codepages {
            get {
                return ((bool)(this["opt_Lookup_Codepages"]));
            }
            set {
                this["opt_Lookup_Codepages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool opt_Lookup_MIMEtypes {
            get {
                return ((bool)(this["opt_Lookup_MIMEtypes"]));
            }
            set {
                this["opt_Lookup_MIMEtypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" />")]
        public global::System.Collections.Specialized.StringCollection local_MIMETYPEs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["local_MIMETYPEs"]));
            }
            set {
                this["local_MIMETYPEs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>utf-8</string>
  <string>utf-16</string>
  <string>windows-1250</string>
  <string>windows-1252</string>
  <string>us-ascii</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection local_CODEPAGEs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["local_CODEPAGEs"]));
            }
            set {
                this["local_CODEPAGEs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>en-US</string>\r\n  <string>en</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection local_CULTUREs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["local_CULTUREs"]));
            }
            set {
                this["local_CULTUREs"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>multi.surbl.org</string>
  <string>multi.uribl.com</string>
  <string>sbl-xbl.spamhaus.org</string>
  <string>bl.spamcop.net</string>
  <string>cbl.abuseat.org</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection common_DNSBL {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["common_DNSBL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" />")]
        public global::System.Collections.Specialized.StringCollection cache_MIMETYPEs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["cache_MIMETYPEs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" />")]
        public global::System.Collections.Specialized.StringCollection cache_CULTUREs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["cache_CULTUREs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" />")]
        public global::System.Collections.Specialized.StringCollection cache_CODEPAGEs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["cache_CODEPAGEs"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool opt_ShowSpamHeaders {
            get {
                return ((bool)(this["opt_ShowSpamHeaders"]));
            }
            set {
                this["opt_ShowSpamHeaders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool opt_ThreadedProcessing {
            get {
                return ((bool)(this["opt_ThreadedProcessing"]));
            }
            set {
                this["opt_ThreadedProcessing"] = value;
            }
        }
    }
}
