//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutlookSafetyChex.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("at_Mm5SiLNB5t7g5C10lFuKlElIGFfFi")]
        public string WhoisXml_ApiKey {
            get {
                return ((string)(this["WhoisXml_ApiKey"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool opt_Use_CACHE {
            get {
                return ((bool)(this["opt_Use_CACHE"]));
            }
            set {
                this["opt_Use_CACHE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool opt_Lookup_WHOIS {
            get {
                return ((bool)(this["opt_Lookup_WHOIS"]));
            }
            set {
                this["opt_Lookup_WHOIS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool opt_Lookup_DNSBL {
            get {
                return ((bool)(this["opt_Lookup_DNSBL"]));
            }
            set {
                this["opt_Lookup_DNSBL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool opt_Lookup_HIBP {
            get {
                return ((bool)(this["opt_Lookup_HIBP"]));
            }
            set {
                this["opt_Lookup_HIBP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool opt_Force_REFRESH {
            get {
                return ((bool)(this["opt_Force_REFRESH"]));
            }
            set {
                this["opt_Force_REFRESH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool opt_Lookup_CONTACTS {
            get {
                return ((bool)(this["opt_Lookup_CONTACTS"]));
            }
            set {
                this["opt_Lookup_CONTACTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool opt_Flag_UNKNOWN_CONTACTS {
            get {
                return ((bool)(this["opt_Flag_UNKNOWN_CONTACTS"]));
            }
            set {
                this["opt_Flag_UNKNOWN_CONTACTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool opt_Local_BLACKLIST {
            get {
                return ((bool)(this["opt_Local_BLACKLIST"]));
            }
            set {
                this["opt_Local_BLACKLIST"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool opt_Local_WHITELIST {
            get {
                return ((bool)(this["opt_Local_WHITELIST"]));
            }
            set {
                this["opt_Local_WHITELIST"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool opt_DeepInspect_LINKS {
            get {
                return ((bool)(this["opt_DeepInspect_LINKS"]));
            }
            set {
                this["opt_DeepInspect_LINKS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool opt_DeepInspect_ATTACHMENTS {
            get {
                return ((bool)(this["opt_DeepInspect_ATTACHMENTS"]));
            }
            set {
                this["opt_DeepInspect_ATTACHMENTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool test_Contacts {
            get {
                return ((bool)(this["test_Contacts"]));
            }
            set {
                this["test_Contacts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool test_Routes {
            get {
                return ((bool)(this["test_Routes"]));
            }
            set {
                this["test_Routes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool test_Links {
            get {
                return ((bool)(this["test_Links"]));
            }
            set {
                this["test_Links"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool test_Attachments {
            get {
                return ((bool)(this["test_Attachments"]));
            }
            set {
                this["test_Attachments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".cn;.tk;.ru;.cm;.jp;.in")]
        public string local_Blacklist {
            get {
                return ((string)(this["local_Blacklist"]));
            }
            set {
                this["local_Blacklist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".org;.net;.com;.edu;.gov;.mil;.us;.uk;.ca;.nyc;.co;bit.ly;goog.le")]
        public string local_Whitelist {
            get {
                return ((string)(this["local_Whitelist"]));
            }
            set {
                this["local_Whitelist"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".org;.net;.com;.edu;.gov;.mil;.us;.uk;.ca;.nyc;.co;bit.ly;goog.le")]
        public string base_Whitelist {
            get {
                return ((string)(this["base_Whitelist"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".cn;.tk;.ru;.cm;.jp;.in")]
        public string base_Blacklist {
            get {
                return ((string)(this["base_Blacklist"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(";")]
        public string list_Delimiter {
            get {
                return ((string)(this["list_Delimiter"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection TLD_cache {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TLD_cache"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool test_Body {
            get {
                return ((bool)(this["test_Body"]));
            }
            set {
                this["test_Body"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public uint log_Level {
            get {
                return ((uint)(this["log_Level"]));
            }
            set {
                this["log_Level"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool opt_ShowLog {
            get {
                return ((bool)(this["opt_ShowLog"]));
            }
            set {
                this["opt_ShowLog"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>multi.surbl.org</string>
  <string>multi.uribl.com</string>
  <string>sbl-xbl.spamhaus.org</string>
  <string>bl.spamcop.net</string>
  <string>cbl.abuseat.org</string>
  <string>multirbl.valli.org</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DNSBL_sites {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DNSBL_sites"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>text/html</string>
  <string>text/plain</string>
  <string>application/rtf</string>
  <string>multipart/alternative</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection common_MIMETYPEs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["common_MIMETYPEs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>utf-8</string>
  <string>utf-16</string>
  <string>windows-1250</string>
  <string>windows-1252</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection common_CODEPAGEs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["common_CODEPAGEs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>8bit</string>\r\n  <string>quoted-printable</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection common_ENCODINGs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["common_ENCODINGs"]));
            }
        }
    }
}
