//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutlookSafetyChecks.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("at_Mm5SiLNB5t7g5C10lFuKlElIGFfFi")]
        public string WhoisXml_ApiKey {
            get {
                return ((string)(this["WhoisXml_ApiKey"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool opt_Use_CACHE {
            get {
                return ((bool)(this["opt_Use_CACHE"]));
            }
            set {
                this["opt_Use_CACHE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool opt_Lookup_WHOIS {
            get {
                return ((bool)(this["opt_Lookup_WHOIS"]));
            }
            set {
                this["opt_Lookup_WHOIS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool opt_Lookup_DNSBL {
            get {
                return ((bool)(this["opt_Lookup_DNSBL"]));
            }
            set {
                this["opt_Lookup_DNSBL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool opt_Lookup_HIBP {
            get {
                return ((bool)(this["opt_Lookup_HIBP"]));
            }
            set {
                this["opt_Lookup_HIBP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool opt_Force_REFRESH {
            get {
                return ((bool)(this["opt_Force_REFRESH"]));
            }
            set {
                this["opt_Force_REFRESH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool opt_Lookup_CONTACTS {
            get {
                return ((bool)(this["opt_Lookup_CONTACTS"]));
            }
            set {
                this["opt_Lookup_CONTACTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool opt_Flag_UNKNOWN_CONTACTS {
            get {
                return ((bool)(this["opt_Flag_UNKNOWN_CONTACTS"]));
            }
            set {
                this["opt_Flag_UNKNOWN_CONTACTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool opt_Local_BLACKLIST {
            get {
                return ((bool)(this["opt_Local_BLACKLIST"]));
            }
            set {
                this["opt_Local_BLACKLIST"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool opt_Local_WHITELIST {
            get {
                return ((bool)(this["opt_Local_WHITELIST"]));
            }
            set {
                this["opt_Local_WHITELIST"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool opt_DeepInspect_LINKS {
            get {
                return ((bool)(this["opt_DeepInspect_LINKS"]));
            }
            set {
                this["opt_DeepInspect_LINKS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool opt_DeepInspect_ATTACHMENTS {
            get {
                return ((bool)(this["opt_DeepInspect_ATTACHMENTS"]));
            }
            set {
                this["opt_DeepInspect_ATTACHMENTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool test_Contacts {
            get {
                return ((bool)(this["test_Contacts"]));
            }
            set {
                this["test_Contacts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool test_Routes {
            get {
                return ((bool)(this["test_Routes"]));
            }
            set {
                this["test_Routes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool test_Links {
            get {
                return ((bool)(this["test_Links"]));
            }
            set {
                this["test_Links"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool test_Attachments {
            get {
                return ((bool)(this["test_Attachments"]));
            }
            set {
                this["test_Attachments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".cn;.tk;.ru;.cm;.jp")]
        public string local_Blacklist {
            get {
                return ((string)(this["local_Blacklist"]));
            }
            set {
                this["local_Blacklist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".org;.net;.com;.edu;.gov;.mil;.us;.uk;.ca;.nyc;.co;bit.ly;goog.le")]
        public string local_Whitelist {
            get {
                return ((string)(this["local_Whitelist"]));
            }
            set {
                this["local_Whitelist"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".org;.net;.com;.edu;.gov;.mil;.us;.uk;.ca;.nyc;.co;bit.ly;goog.le")]
        public string base_Whitelist {
            get {
                return ((string)(this["base_Whitelist"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".cn;.tk;.ru;.cm;.jp")]
        public string base_Blacklist {
            get {
                return ((string)(this["base_Blacklist"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(";")]
        public string list_Delimiter {
            get {
                return ((string)(this["list_Delimiter"]));
            }
        }
    }
}
